/*
 * Copyright (C) 2021 GS United Labs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 *  Project    :   NTA-Basic
 *  Class      :   AccountingOptionsPanel.java
 *  Author     :   Sean Carrick
 *  Created    :   Oct 28, 2021 @ 8:13:41 PM
 *  Modified   :   Oct 28, 2021
 * 
 *  Purpose:     See class JavaDoc comment.
 * 
 *  Revision History:
 * 
 *  WHEN          BY                   REASON
 *  ------------  -------------------  -----------------------------------------
 *  Oct 28, 2021  Sean Carrick         Initial creation.
 * *****************************************************************************
 */
package com.gs.nta.accounting.options;

import com.gs.nta.api.OptionsCategories;
import com.gs.nta.api.OptionsPanelProvider;
import com.gs.nta.utils.Properties;
import javax.swing.JPanel;

/**
 *
 * @author Sean Carrick
 */
public class AccountingOptionsPanel extends javax.swing.JPanel implements OptionsPanelProvider {
    
    private static JPanel panel;
    
    /**
     * Creates new form AccountingOptions
     */
    public AccountingOptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountingPeriods = new javax.swing.JPanel();
        periodStartLabel = new javax.swing.JLabel();
        periodStartMonthList = new javax.swing.JComboBox<>();
        periodStartYearLabel = new javax.swing.JLabel();
        periodStartYearField = new javax.swing.JFormattedTextField();
        xtraMonthCheckbox = new javax.swing.JCheckBox();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AccountingOptionsPanel.class);
        accountingPeriods.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("accountingPeriods.border.title"))); // NOI18N

        periodStartLabel.setText(resourceMap.getString("periodStartLabel.text")); // NOI18N

        periodStartMonthList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month...", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        periodStartYearLabel.setText(resourceMap.getString("periodStartYearLabel.text")); // NOI18N

        periodStartYearField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));

        xtraMonthCheckbox.setText(resourceMap.getString("xtraMonthCheckbox.text")); // NOI18N

        javax.swing.GroupLayout accountingPeriodsLayout = new javax.swing.GroupLayout(accountingPeriods);
        accountingPeriods.setLayout(accountingPeriodsLayout);
        accountingPeriodsLayout.setHorizontalGroup(
            accountingPeriodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountingPeriodsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(periodStartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodStartMonthList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(periodStartYearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodStartYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xtraMonthCheckbox)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        accountingPeriodsLayout.setVerticalGroup(
            accountingPeriodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountingPeriodsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountingPeriodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodStartLabel)
                    .addComponent(periodStartMonthList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodStartYearLabel)
                    .addComponent(periodStartYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xtraMonthCheckbox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountingPeriods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountingPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public OptionsCategories getCategory() {
        return OptionsCategories.ACCOUNTING;
    }

    @Override
    public JPanel getInstance() {

        if (panel == null) {
            panel = new AccountingOptionsPanel();
        }
        
        return panel;
    }

    @Override
    public String getTitle() {
        return "Defaults";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountingPeriods;
    private javax.swing.JLabel periodStartLabel;
    private javax.swing.JComboBox<String> periodStartMonthList;
    private javax.swing.JFormattedTextField periodStartYearField;
    private javax.swing.JLabel periodStartYearLabel;
    private javax.swing.JCheckBox xtraMonthCheckbox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void saveSettings(Properties properties) {
    }

    @Override
    public void loadSettings(Properties properties) {
    }
}
