/*
 * Copyright (C) 2021 GS United Labs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 *  Project    :   NTA-Basic
 *  Class      :   AboutDialog.java
 *  Author     :   Sean Carrick
 *  Created    :   Oct 29, 2021 @ 1:22:51 PM
 *  Modified   :   Oct 29, 2021
 * 
 *  Purpose:     See class JavaDoc comment.
 * 
 *  Revision History:
 * 
 *  WHEN          BY                   REASON
 *  ------------  -------------------  -----------------------------------------
 *  Oct 29, 2021  Sean Carrick         Initial creation.
 * *****************************************************************************
 */
package com.gs.nta.desktop;

import com.gs.nta.desktop.panels.AboutModulePanel;
import com.gs.nta.api.AboutPanelProvider;
import java.util.ServiceLoader;
import org.jdesktop.application.Application;
import org.jdesktop.application.ApplicationContext;

/**
 *
 * @author Sean Carrick
 */
public class AboutDialog extends javax.swing.JDialog {
    
    private ApplicationContext context;

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        context = Application.getInstance().getContext();
        
        initComponents();
        
        copyrightPanel.select(0, 0);
        
        loadAboutPanels();
    }
    
    private void loadAboutPanels() {
        ServiceLoader<AboutPanelProvider> loader = ServiceLoader.load(AboutPanelProvider.class);
        
        if (loader != null) {
            for (AboutPanelProvider p : loader) {
                AboutModulePanel panel = new AboutModulePanel();
                panel.setCopyright("<html>" + p.getCopyright());
                panel.setLicenseURL(p.getLicenseURL());
                panel.setLogo(p.getLogo());
                panel.setVendor(p.getVendor());

                for (String contrib : p.getContributors()) {
                    panel.addContributor(contrib);
                }

                modulesPanel.add(panel);
                modulesPanel.setTitleAt(modulesPanel.getTabCount() - 1, p.getTitle());
            }
        }
        
        if (modulesPanel.getTabCount() >= 1) {
            modulesPanel.setSelectedIndex(0);
            modulesPanel.setVisible(true);
        } else {
            modulesPanel.setVisible(false);
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ntaLogoLabel = new javax.swing.JLabel();
        aboutModulesPanel = new javax.swing.JPanel();
        modulesPanel = new javax.swing.JTabbedPane();
        titleLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        copyrightPanel = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AboutDialog.class);
        ntaLogoLabel.setIcon(resourceMap.getIcon("ntaLogoLabel.icon")); // NOI18N
        ntaLogoLabel.setName("ntaLogoLabel"); // NOI18N

        aboutModulesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("aboutModulesPanel.border.title"))); // NOI18N
        aboutModulesPanel.setName("aboutModulesPanel"); // NOI18N

        modulesPanel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        modulesPanel.setName("modulesPanel"); // NOI18N

        javax.swing.GroupLayout aboutModulesPanelLayout = new javax.swing.GroupLayout(aboutModulesPanel);
        aboutModulesPanel.setLayout(aboutModulesPanelLayout);
        aboutModulesPanelLayout.setHorizontalGroup(
            aboutModulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modulesPanel)
        );
        aboutModulesPanelLayout.setVerticalGroup(
            aboutModulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );

        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N

        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
        versionLabel.setName("versionLabel"); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        copyrightPanel.setEditable(false);
        copyrightPanel.setContentType("text/html"); // NOI18N
        copyrightPanel.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0; fontsize: 8pt\">\nCopyright&copy; 2007-2021 GS United Labs. All rights under copyright reserved.</p> <p style=\"fontsize:8pt\">Northwind Traders Basic Edition and the NTA Platform are released under the GNU General Public License version 3.0.</p> <p style=\"fontsize: 9pt\">Northwind Traders Basic Edition and the NTA Platform are free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.</p> <p style=\"fontsize: 9pt\">This program is distributed in the hope that it will be useful, but <strong>WITHOUT ANY WARRANTY</strong>; without even the implied warranty of <strong>MERCHANTABILITY</strong> or <strong>FITNESS FOR A PARTICULAR PURPOSE</strong>. See the GNU General Public License for more details.</p> <p style=\"fontsize: 9pt\">You should have received a copy of the GNU General Public License along with this program. If not, see <a href=\"https://www.gnu.org/licenses/\">https://www.gnu.org/licenses/</a>.\n    </p>\n  </body>\n</html>\n"); // NOI18N
        copyrightPanel.setName("copyrightPanel"); // NOI18N
        jScrollPane1.setViewportView(copyrightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutModulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ntaLogoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(versionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ntaLogoLabel))
                .addGap(18, 18, 18)
                .addComponent(aboutModulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutModulesPanel;
    private javax.swing.JEditorPane copyrightPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane modulesPanel;
    private javax.swing.JLabel ntaLogoLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
