/*
 * Copyright (C) 2021 GS United Labs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 *  Project    :   NTA-Basic
 *  Class      :   AboutModulePanel.java
 *  Author     :   Sean Carrick
 *  Created    :   Oct 29, 2021 @ 1:58:04 PM
 *  Modified   :   Oct 29, 2021
 * 
 *  Purpose:     See class JavaDoc comment.
 * 
 *  Revision History:
 * 
 *  WHEN          BY                   REASON
 *  ------------  -------------------  -----------------------------------------
 *  Oct 29, 2021  Sean Carrick         Initial creation.
 * *****************************************************************************
 */
package com.gs.nta.desktop.panels;

import com.gs.nta.utils.MessageBox;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Sean Carrick
 */
public class AboutModulePanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutModulePanel
     */
    public AboutModulePanel() {
        initComponents();
    }
    
    public void setLogo(ImageIcon logo) {
        logoLabel.setIcon(logo);
    }
    
    public void setVendor(String vendor) {
        vendorField.setText(vendor);
    }
    
    public void setCopyright(String copyright) {
        copyrightField.setText(copyright);
    }
    
    public void setLicenseURL(URL licenseURL) {
        linkedLabel.setText(licenseURL.toString());
    }
    
    public void addContributor(String contributor) {
        contributorsField.append(contributor + "\n");
        contributorsField.select(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        vendorLabel = new javax.swing.JLabel();
        vendorField = new javax.swing.JLabel();
        copyRightLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        copyrightField = new javax.swing.JLabel();
        licenseURLLabel = new javax.swing.JLabel();
        linkedLabel = new javax.swing.JLabel();
        contributorsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contributorsField = new javax.swing.JTextArea();

        logoLabel.setMaximumSize(new java.awt.Dimension(48, 48));
        logoLabel.setMinimumSize(new java.awt.Dimension(48, 48));
        logoLabel.setName("logoLabel"); // NOI18N
        logoLabel.setPreferredSize(new java.awt.Dimension(48, 48));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AboutModulePanel.class);
        vendorLabel.setText(resourceMap.getString("vendorLabel.text")); // NOI18N
        vendorLabel.setName("vendorLabel"); // NOI18N

        vendorField.setName("vendorField"); // NOI18N

        copyRightLabel.setText(resourceMap.getString("copyRightLabel.text")); // NOI18N
        copyRightLabel.setName("copyRightLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        copyrightField.setName("copyrightField"); // NOI18N
        jScrollPane1.setViewportView(copyrightField);

        licenseURLLabel.setText(resourceMap.getString("licenseURLLabel.text")); // NOI18N
        licenseURLLabel.setName("licenseURLLabel"); // NOI18N

        linkedLabel.setForeground(new java.awt.Color(0, 0, 153));
        linkedLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkedLabel.setName("linkedLabel"); // NOI18N
        linkedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkedLabelMouseClicked(evt);
            }
        });

        contributorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("contributorsPanel.border.title"))); // NOI18N
        contributorsPanel.setName("contributorsPanel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        contributorsField.setColumns(20);
        contributorsField.setRows(5);
        contributorsField.setName("contributorsField"); // NOI18N
        jScrollPane2.setViewportView(contributorsField);

        javax.swing.GroupLayout contributorsPanelLayout = new javax.swing.GroupLayout(contributorsPanel);
        contributorsPanel.setLayout(contributorsPanelLayout);
        contributorsPanelLayout.setHorizontalGroup(
            contributorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        contributorsPanelLayout.setVerticalGroup(
            contributorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(licenseURLLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vendorLabel)
                                    .addComponent(copyRightLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendorField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(linkedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(contributorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorLabel)
                            .addComponent(vendorField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyRightLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseURLLabel)
                    .addComponent(linkedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contributorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void linkedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedLabelMouseClicked
        MessageBox.showWarning("Need to implement launching the default browser "
                + "to go to the wesite in this label's text property.", 
                "Implementation Needed");
    }//GEN-LAST:event_linkedLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contributorsField;
    private javax.swing.JPanel contributorsPanel;
    private javax.swing.JLabel copyRightLabel;
    private javax.swing.JLabel copyrightField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel licenseURLLabel;
    private javax.swing.JLabel linkedLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel vendorField;
    private javax.swing.JLabel vendorLabel;
    // End of variables declaration//GEN-END:variables
}
