/*
 * Copyright (C) 2021 GS United Labs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 *  Project    :   NTA-Basic
 *  Class      :   ProxyOptionsPanel.java
 *  Author     :   Sean Carrick
 *  Created    :   Oct 28, 2021 @ 4:55:18 PM
 *  Modified   :   Oct 28, 2021
 * 
 *  Purpose:     See class JavaDoc comment.
 * 
 *  Revision History:
 * 
 *  WHEN          BY                   REASON
 *  ------------  -------------------  -----------------------------------------
 *  Oct 28, 2021  Sean Carrick         Initial creation.
 * *****************************************************************************
 */
package com.gs.nta.desktop.panels;

import com.gs.nta.NTApp;
import com.gs.nta.api.OptionsCategories;
import com.gs.nta.api.OptionsPanelProvider;
import com.gs.nta.utils.Properties;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.application.Application;

/**
 *
 * @author Sean Carrick
 */
public class ProxyOptionsPanel extends javax.swing.JPanel 
        implements OptionsPanelProvider, DocumentListener {
    
    private static ProxyOptionsPanel panel;
    private static NTApp app;
    private static PropertyChangeSupport pcs;

    /**
     * Creates new form ProxyOptionsPanel
     */
    public ProxyOptionsPanel() {
        initComponents();
        
        app = (NTApp) Application.getInstance();
        pcs = new PropertyChangeSupport(this);
        
        systemProxyRadioButton.setSelected(Boolean.parseBoolean(
                System.getProperty("java.net.useSystemProxies")));
        
        proxyServerField.getDocument().addDocumentListener(this);
        
        loadSettings(app.getProperties());
    }
    
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        pcs.addPropertyChangeListener(listener);
    }
    
    public void addPropertyChangeListener(String propertyName, 
            PropertyChangeListener listener) {
        pcs.addPropertyChangeListener(propertyName, listener);
    }
    
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        pcs.removePropertyChangeListener(listener);
    }
    
    public void removePropertyChangeListener(String propertyName, 
            PropertyChangeListener listener) {
        pcs.removePropertyChangeListener(propertyName, listener);
    }
    
    public void firePropertyChange(String propertyName, Object oldValue, 
            Object newValue) {
        if (propertyName != null && oldValue != null && newValue != null) {
            pcs.firePropertyChange(propertyName, oldValue, newValue);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proxyGroup = new javax.swing.ButtonGroup();
        statsInfoLabel = new javax.swing.JLabel();
        allowStatisticsCheckBox = new javax.swing.JCheckBox();
        usageStatsLabel = new javax.swing.JLabel();
        testConnectionButton = new javax.swing.JButton();
        moreProxyOptionsButton = new javax.swing.JButton();
        proxyPortField = new javax.swing.JTextField();
        proxyPortLabel = new javax.swing.JLabel();
        proxyServerField = new javax.swing.JTextField();
        httpProxyLabel = new javax.swing.JLabel();
        manuProxyRadioButton = new javax.swing.JRadioButton();
        systemProxyRadioButton = new javax.swing.JRadioButton();
        reloadButton = new javax.swing.JButton();
        noProxyRadioButton = new javax.swing.JRadioButton();
        proxySettingsLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        webBrowserLabel = new javax.swing.JLabel();
        webBrowsersList = new javax.swing.JComboBox<>();
        editBrowserListButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ProxyOptionsPanel.class);
        statsInfoLabel.setText(resourceMap.getString("statsInfoLabel.text")); // NOI18N
        statsInfoLabel.setName("statsInfoLabel"); // NOI18N

        allowStatisticsCheckBox.setText(resourceMap.getString("allowStatisticsCheckBox.text")); // NOI18N
        allowStatisticsCheckBox.setName("allowStatisticsCheckBox"); // NOI18N
        allowStatisticsCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                allowStatisticsCheckBoxItemStateChanged(evt);
            }
        });

        usageStatsLabel.setText(resourceMap.getString("usageStatsLabel.text")); // NOI18N
        usageStatsLabel.setName("usageStatsLabel"); // NOI18N

        testConnectionButton.setText(resourceMap.getString("testConnectionButton.text")); // NOI18N
        testConnectionButton.setName("testConnectionButton"); // NOI18N

        moreProxyOptionsButton.setText(resourceMap.getString("moreProxyOptionsButton.text")); // NOI18N
        moreProxyOptionsButton.setEnabled(false);
        moreProxyOptionsButton.setName("moreProxyOptionsButton"); // NOI18N

        proxyPortField.setEnabled(false);
        proxyPortField.setName("proxyPortField"); // NOI18N

        proxyPortLabel.setText(resourceMap.getString("proxyPortLabel.text")); // NOI18N
        proxyPortLabel.setEnabled(false);
        proxyPortLabel.setName("proxyPortLabel"); // NOI18N

        proxyServerField.setEnabled(false);
        proxyServerField.setName("proxyServerField"); // NOI18N

        httpProxyLabel.setText(resourceMap.getString("httpProxyLabel.text")); // NOI18N
        httpProxyLabel.setEnabled(false);
        httpProxyLabel.setName("httpProxyLabel"); // NOI18N

        proxyGroup.add(manuProxyRadioButton);
        manuProxyRadioButton.setText(resourceMap.getString("manuProxyRadioButton.text")); // NOI18N
        manuProxyRadioButton.setName("manuProxyRadioButton"); // NOI18N
        manuProxyRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                manuProxyRadioButtonItemStateChanged(evt);
            }
        });

        proxyGroup.add(systemProxyRadioButton);
        systemProxyRadioButton.setText(resourceMap.getString("systemProxyRadioButton.text")); // NOI18N
        systemProxyRadioButton.setName("systemProxyRadioButton"); // NOI18N
        systemProxyRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                systemProxyRadioButtonItemStateChanged(evt);
            }
        });

        reloadButton.setIcon(resourceMap.getIcon("reloadButton.icon")); // NOI18N
        reloadButton.setText(resourceMap.getString("reloadButton.text")); // NOI18N
        reloadButton.setName("reloadButton"); // NOI18N

        proxyGroup.add(noProxyRadioButton);
        noProxyRadioButton.setSelected(true);
        noProxyRadioButton.setText(resourceMap.getString("noProxyRadioButton.text")); // NOI18N
        noProxyRadioButton.setName("noProxyRadioButton"); // NOI18N
        noProxyRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noProxyRadioButtonItemStateChanged(evt);
            }
        });

        proxySettingsLabel.setText(resourceMap.getString("proxySettingsLabel.text")); // NOI18N
        proxySettingsLabel.setName("proxySettingsLabel"); // NOI18N

        jSeparator3.setName("jSeparator3"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        webBrowserLabel.setText(resourceMap.getString("webBrowserLabel.text")); // NOI18N
        webBrowserLabel.setName("webBrowserLabel"); // NOI18N

        webBrowsersList.setName("webBrowsersList"); // NOI18N
        webBrowsersList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                webBrowsersListItemStateChanged(evt);
            }
        });

        editBrowserListButton.setIcon(resourceMap.getIcon("editBrowserListButton.icon")); // NOI18N
        editBrowserListButton.setMnemonic('E');
        editBrowserListButton.setText(resourceMap.getString("editBrowserListButton.text")); // NOI18N
        editBrowserListButton.setName("editBrowserListButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proxySettingsLabel)
                            .addComponent(webBrowserLabel)
                            .addComponent(usageStatsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webBrowsersList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBrowserListButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manuProxyRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(httpProxyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proxyServerField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proxyPortLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proxyPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moreProxyOptionsButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testConnectionButton)
                                    .addComponent(noProxyRadioButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(systemProxyRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reloadButton))
                                    .addComponent(allowStatisticsCheckBox)
                                    .addComponent(statsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webBrowserLabel)
                    .addComponent(webBrowsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBrowserListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxySettingsLabel)
                    .addComponent(noProxyRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(systemProxyRadioButton)
                    .addComponent(reloadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuProxyRadioButton)
                    .addComponent(httpProxyLabel)
                    .addComponent(proxyServerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moreProxyOptionsButton)
                    .addComponent(proxyPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proxyPortLabel))
                .addGap(18, 18, 18)
                .addComponent(testConnectionButton)
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usageStatsLabel)
                    .addComponent(allowStatisticsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manuProxyRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_manuProxyRadioButtonItemStateChanged
        pcs.firePropertyChange("itemStateChanged",
                !manuProxyRadioButton.isSelected(), 
                manuProxyRadioButton.isSelected());

        httpProxyLabel.setEnabled(manuProxyRadioButton.isSelected());
        proxyServerField.setEnabled(manuProxyRadioButton.isSelected());
        proxyPortLabel.setEnabled(manuProxyRadioButton.isSelected());
        proxyPortField.setEnabled(manuProxyRadioButton.isSelected());
        moreProxyOptionsButton.setEnabled(manuProxyRadioButton.isSelected());
    }//GEN-LAST:event_manuProxyRadioButtonItemStateChanged

    private void systemProxyRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_systemProxyRadioButtonItemStateChanged
        pcs.firePropertyChange("itemStateChanged",
                !systemProxyRadioButton.isSelected(), 
                systemProxyRadioButton.isSelected());
        reloadButton.setEnabled(systemProxyRadioButton.isSelected());
        proxyPortField.setText("[Sys]");
        proxyServerField.setText("[use system proxy]");
    }//GEN-LAST:event_systemProxyRadioButtonItemStateChanged

    private void noProxyRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noProxyRadioButtonItemStateChanged
        pcs.firePropertyChange("itemStateChaned", !noProxyRadioButton.isSelected(),
                noProxyRadioButton.isSelected());
    }//GEN-LAST:event_noProxyRadioButtonItemStateChanged

    private void webBrowsersListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_webBrowsersListItemStateChanged
        pcs.firePropertyChange("itemStateChanged", evt.getItem(), 
                evt.getStateChange());
    }//GEN-LAST:event_webBrowsersListItemStateChanged

    private void allowStatisticsCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_allowStatisticsCheckBoxItemStateChanged
        pcs.firePropertyChange("itemStateChanged", 
                !allowStatisticsCheckBox.isSelected(),
                allowStatisticsCheckBox.isSelected());
    }//GEN-LAST:event_allowStatisticsCheckBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allowStatisticsCheckBox;
    private javax.swing.JButton editBrowserListButton;
    private javax.swing.JLabel httpProxyLabel;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton manuProxyRadioButton;
    private javax.swing.JButton moreProxyOptionsButton;
    private javax.swing.JRadioButton noProxyRadioButton;
    private javax.swing.ButtonGroup proxyGroup;
    private javax.swing.JTextField proxyPortField;
    private javax.swing.JLabel proxyPortLabel;
    private javax.swing.JTextField proxyServerField;
    private javax.swing.JLabel proxySettingsLabel;
    private javax.swing.JButton reloadButton;
    private javax.swing.JLabel statsInfoLabel;
    private javax.swing.JRadioButton systemProxyRadioButton;
    private javax.swing.JButton testConnectionButton;
    private javax.swing.JLabel usageStatsLabel;
    private javax.swing.JLabel webBrowserLabel;
    private javax.swing.JComboBox<String> webBrowsersList;
    // End of variables declaration//GEN-END:variables

    @Override
    public OptionsCategories getCategory() {
        return OptionsCategories.GENERAL;
    }

    @Override
    public JPanel getInstance() {
        if (panel == null) {
            panel = new ProxyOptionsPanel();
        }
        
        return panel;
    }

    @Override
    public String getTitle() {
        return "Internet Settings";
    }
    
    @Override
    public void loadSettings(Properties props) {
        proxyServerField.setText(props.getPropertyAsString("net.proxy.server"));
        proxyPortField.setText(props.getPropertyAsString("net.proxy.port"));
        
        noProxyRadioButton.setSelected(props.getProperty("net.usingProxy") == null
                ? !props.getPropertyAsBoolean("net.usingSystemProxy") 
                        && !props.getPropertyAsBoolean("net.usingProxy")
                : !props.getPropertyAsBoolean("net.usingProxy"));
        
        manuProxyRadioButton.setSelected(props.getProperty("net.usingProxy") == null
                ? !props.getPropertyAsBoolean("net.usingSystemProxy") 
                        && !props.getPropertyAsString("net.proxy.server").equals("[using system proxy]")
                        && !props.getPropertyAsString("net.proxy.port").equals("[Sys]")
                : !props.getPropertyAsBoolean("net.usingSystemProxy") 
                        && props.getPropertyAsBoolean("net.usingProxy"));
        
        systemProxyRadioButton.setSelected(props.getProperty("net.usingSystemProxy") == null
                ? true : props.getPropertyAsBoolean("net.usingSystemProxy"));
        
        allowStatisticsCheckBox.setSelected(props.getPropertyAsBoolean("allow.usageStatistics"));
    }
    
    @Override
    public void saveSettings(Properties props) {
        props.setSystemProperty("net.usingProxy", !noProxyRadioButton.isSelected());
        if (manuProxyRadioButton.isSelected()) {
            props.setSystemProperty("net.usingSystemProxy", Boolean.FALSE);
            props.setSystemProperty("net.proxy.server", proxyServerField.getText());
            props.setSystemProperty("net.proxy.port", proxyPortField.getText());
        } else if (systemProxyRadioButton.isSelected()) {
            props.setSystemProperty("net.usingSystemProxy", Boolean.TRUE);
            props.setSystemProperty("net.proxy.server", "[using system proxy]");
            props.setSystemProperty("net.proxy.port", "[Sys]");
        }
        
        props.setSystemProperty("allow.usageStatistics", allowStatisticsCheckBox.isSelected());
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        pcs.firePropertyChange("textChanged", null, null);
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        pcs.firePropertyChange("textChanged", null, null);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        pcs.firePropertyChange("textChanged", null, null);
    }
}
